### ISSUE TITLE
Why using PendingIntent.FLAG_MUTABLE in getPendingSelfIntent method?

### ISSUE THREAD

**Issue by ytheekshana** [JimSeker/widgets#1]
Hi. I am new to this. Can you explain the purpose in using PendingIntent.FLAG_MUTABLE in the getPendingSelfIntent  function. 
What If I were to use PendingIntent.FLAG_IMMUTABLE. What happnes then. Looking forward a reply. Thanks

**Comment by JimSeker** [comment]
starting in api 31 or 32, you had to set that a flag (IMMUTABLE or MUTABLE) for it work in the new android versions.  
the immutable flag means as I understand the pendingintent is a constant and can not be changed.
